sudo: required
dist: trusty
language: cpp

compiler:
    - gcc

before_install:
    - lsb_release -a
    - uname -a
    - sudo apt-get install libmysqlclient-dev -y
    - sudo apt-get install mysql-client -y

install:
    - 

script:
    - cd src/third-party/LFC/
    - chmod 755 Package.sh
    - ./Package.sh
    - tar -zxvf LFC*.tar.gz

after_succesS:
    - 

branches:
    only:
    - master

notifications:
    email: true
