/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_moodwu_taijie_Hello */

#ifndef _Included_com_moodwu_taijie_Hello
#define _Included_com_moodwu_taijie_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_moodwu_taijie_Hello
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moodwu_taijie_Hello_helloWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_moodwu_taijie_Hello
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_moodwu_taijie_Hello_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
